### ISSUE TITLE
Falta punto y coma al final de la sentencia de los tests

### ISSUE THREAD

**Issue by edme88** [Selene-21/edenpageObject#10]
https://github.com/Selene-21/edenpageObject/blob/691eadb3591f6bb47fd97f0e3b432164e89de69e/cypress/e2e/EDEN/eden3.cy.js#L6-L9

**Comment by Selene-21** [comment]
Si, esos los vi cuando estuve haciendo las otras practicas que habías dado. Creo que los corregí, pero ya vuelvo a revisar. Aun reniego para subir los códigos jeje
