### ISSUE TITLE
El describe debería cerrarse al final del archivo (no antes)

### ISSUE THREAD

**Issue by edme88** [Selene-21/edenpageObject#11]
https://github.com/Selene-21/edenpageObject/blob/691eadb3591f6bb47fd97f0e3b432164e89de69e/cypress/e2e/EDEN/eden3.cy.js#L11

**Comment by Selene-21** [comment]
Ya reviso porqué es que quedó así Agus. En la teoría según yo, lo había puesto como me enseñaste.
